
GET https://obscure-chamber-09057.herokuapp.com/register

###
# Register as a Vendor
POST http://localhost:5000/register/vendor
Content-Type: application/json

{ 
    "email": "zde23e90@gmail.com",
    "password": "12345",
    "name": "Afeez Olawale",
    "location": "Ilorin, Nigeria"
}

###

# Register as a buyer
POST http://localhost:5000/register/buyer

Content-Type: application/json

{
    
    "email": "afeezdev@gmail.com",
    "password": "12345",
    "name": "Afeez Olawale"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "afeezdev@gmail.com",
    "password": "12345"
}


###

POST http://localhost:5000/food-menu
Content-Type: application/json

{
    "email": "zde23e90@gmail.com",
    "food": "Meateeee",
    "price": "#300"
}

###

POST http://localhost:5000/order
Content-Type: application/json

{
    "email": "afeezdev4@gmail.com",
    "food": "Meat"
}

###


POST  http://localhost:5500/food-search
Content-Type: application/json

{
    "location": "Abuja"
}

###

